#!/bin/bash

read -p "Select 1 for my_data and 2 for udacity_sample_data and 3 for removing data : " input_choice

if [ "$input_choice" = "1" ]
then
    wget -O followme_data.tar.gz "https://drive.google.com/uc?export=download&id=1YgZYH7uFL5ouSFhUqyfOsO-YlfRo9EJo"
    tar -xzf followme_data.tar.gz
    rm -rf followme_data.tar.gz
    mv followme_data/* .
    rm -rf followme_data
elif [ "$input_choice" = "2" ]
then
    wget -O udacity_data.tar.gz "https://drive.google.com/uc?export=download&id=1bradvxaHYnn2HB2V7q7ZUKaIIBjyDIOC"     	  
    tar -xzf udacity_data.tar.gz
    rm -rf udacity_data.tar.gz
elif [ "$input_choice" = "3" ]
then
    rm -rf train
    rm -rf validation
    rm -rf sample_evaluation_data
    rm -rf runs
else
    echo "Not acceptable option"
fi




